import HeaderWrapper from "@/components/HeaderWrapper";
import UserNetworkController from "@/components/root-controller/UserNetworkController";
import type { Metadata } from "next";
import iranSansLocal from "next/font/local";
import "./globals.css"
import ProviderApp from "./ProviderApp";

const iranSans = iranSansLocal({
  src: "../assets/fonts/IRANSansWeb(FaNum).woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="rtl"
        className={`${iranSans.className} antialiased bg-lightGray`}
      >
        <div className="holder-container min-[1550px]:w-[1500px] m-auto">
          <ProviderApp>
            <UserNetworkController>
              <HeaderWrapper />
            </UserNetworkController>
            <div className="holder px-10 max-lg:px-0">
              {children}
            </div>
          </ProviderApp>
        </div>
      </body>
    </html>
  );
}
